# Generated by Django 4.1 on 2022-08-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_kierownicy_alter_administracja_user_delete_kierownik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kierownicy',
            name='User',
        ),
        migrations.DeleteModel(
            name='Administracja',
        ),
        migrations.DeleteModel(
            name='Kierownicy',
        ),
    ]
