# Generated by Django 4.1 on 2022-08-16 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budowa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=128)),
                ('typ', models.CharField(max_length=128)),
                ('podwykonawca', models.CharField(max_length=128)),
                ('kierownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kierownik', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Przetarg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=128)),
                ('adres', models.CharField(max_length=128)),
                ('typ_budowy', models.CharField(max_length=128)),
                ('typ_budynku', models.CharField(max_length=128)),
                ('zleceniodawca', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Wydatki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MainChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudowaChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('budowa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.budowa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='budowa',
            name='wydatki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.wydatki'),
        ),
    ]
