# Generated by Django 4.1 on 2022-08-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budowa',
            name='kierownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.kierownik'),
        ),
    ]
