# Generated by Django 4.1 on 2022-08-17 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0002_alter_budowa_kierownik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budowa',
            name='kierownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kierownik', to=settings.AUTH_USER_MODEL),
        ),
    ]
