# Generated by Django 4.1 on 2022-08-18 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_budowa_kierownik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budowa',
            name='wydatki',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_app.wydatki'),
        ),
    ]
