# Generated by Django 4.1 on 2022-08-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_budowa_wydatki'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budowa',
            name='wydatki',
        ),
        migrations.AddField(
            model_name='budowa',
            name='budzet',
            field=models.IntegerField(default=0, max_length=128),
        ),
    ]
