# Generated by Django 4.1 on 2022-08-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_remove_budowa_wydatki_budowa_budzet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='przetarg',
            old_name='adres',
            new_name='kod_pocztowy',
        ),
        migrations.RemoveField(
            model_name='budowa',
            name='adres',
        ),
        migrations.AddField(
            model_name='budowa',
            name='kod_pocztowy',
            field=models.CharField(default='brak', max_length=128),
        ),
        migrations.AddField(
            model_name='budowa',
            name='miasto',
            field=models.CharField(default='brak', max_length=128),
        ),
        migrations.AddField(
            model_name='budowa',
            name='ulica',
            field=models.CharField(default='brak', max_length=128),
        ),
        migrations.AddField(
            model_name='przetarg',
            name='miasto',
            field=models.CharField(default='brak', max_length=128),
        ),
        migrations.AddField(
            model_name='przetarg',
            name='ulica',
            field=models.CharField(default='brak', max_length=128),
        ),
        migrations.AlterField(
            model_name='budowa',
            name='budzet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='przetarg',
            name='nazwa',
            field=models.CharField(default='brak', max_length=128),
        ),
    ]
