# Generated by Django 4.1 on 2022-08-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_rename_adres_przetarg_kod_pocztowy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budowa',
            name='kod_pocztowy',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='budowa',
            name='miasto',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='budowa',
            name='ulica',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='przetarg',
            name='miasto',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='przetarg',
            name='nazwa',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='przetarg',
            name='ulica',
            field=models.CharField(max_length=128),
        ),
    ]
