# Generated by Django 4.1 on 2022-08-18 18:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0007_alter_budowa_kod_pocztowy_alter_budowa_miasto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BudowaChat',
            new_name='BudowaUpdate',
        ),
        migrations.RenameModel(
            old_name='MainChat',
            new_name='MainUpdate',
        ),
    ]
