# Generated by Django 4.1 on 2022-08-19 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_rename_budowachat_budowaupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wydatki',
            name='budowa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin_app.budowa'),
        ),
        migrations.AddField(
            model_name='wydatki',
            name='inne',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wydatki',
            name='materialy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wydatki',
            name='pensje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wydatki',
            name='pozwolenia',
            field=models.IntegerField(default=0),
        ),
    ]
