# Generated by Django 4.1 on 2022-08-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_wydatki_budowa_wydatki_inne_wydatki_materialy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wydatki',
            name='inne',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='wydatki',
            name='materialy',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='wydatki',
            name='pensje',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='wydatki',
            name='pozwolenia',
            field=models.IntegerField(default=None),
        ),
    ]
