# Generated by Django 4.1 on 2022-08-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_alter_wydatki_inne_alter_wydatki_materialy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='przetarg',
            name='budzet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budowa',
            name='budzet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wydatki',
            name='inne',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='wydatki',
            name='materialy',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='wydatki',
            name='pensje',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='wydatki',
            name='pozwolenia',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
