# Generated by Django 4.1 on 2022-08-19 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_przetarg_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='wydatki',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
