# Generated by Django 4.1 on 2022-08-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_wydatki_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wydatki',
            name='data',
        ),
        migrations.AlterField(
            model_name='przetarg',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
