# Generated by Django 4.1 on 2022-08-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_remove_wydatki_data_alter_przetarg_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wydatki',
            name='inne',
        ),
        migrations.RemoveField(
            model_name='wydatki',
            name='materialy',
        ),
        migrations.RemoveField(
            model_name='wydatki',
            name='pensje',
        ),
        migrations.RemoveField(
            model_name='wydatki',
            name='pozwolenia',
        ),
        migrations.AddField(
            model_name='wydatki',
            name='kategoria',
            field=models.IntegerField(choices=[(0, 'brak'), (1, 'materiały'), (2, 'narzedzia'), (3, 'pensje'), (4, 'podwykonawca'), (5, 'odpady')], default=0),
        ),
        migrations.AddField(
            model_name='wydatki',
            name='kwota',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
