# Generated by Django 4.1 on 2022-08-19 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_remove_wydatki_inne_remove_wydatki_materialy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wydatki',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
