# Generated by Django 4.1 on 2022-08-20 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_wydatki_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wydatki',
            name='budowa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.budowa'),
        ),
    ]
