# Generated by Django 4.1 on 2022-08-21 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_alter_wydatki_kategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='przetarg',
            name='dodanie',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='przetarg',
            name='data',
            field=models.DateField(blank=True),
        ),
    ]
