# Generated by Django 4.1 on 2022-08-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_przetarg_dodanie_alter_przetarg_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przetarg',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
