# Generated by Django 4.1 on 2022-08-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0021_alter_przetarg_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przetarg',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data(mm/dd/yy)'),
        ),
    ]
