# Generated by Django 4.1 on 2022-08-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0022_alter_przetarg_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='budowa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
