# Generated by Django 4.1 on 2022-08-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0023_budowa_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przetarg',
            name='budzet',
            field=models.PositiveIntegerField(default='budzet'),
        ),
    ]
