# Generated by Django 4.1 on 2022-08-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0025_alter_przetarg_budzet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wydatki',
            name='kategoria',
            field=models.IntegerField(choices=[(1, 'MATERIAŁY'), (2, 'NARZĘDZIA'), (3, 'PENSJE'), (4, 'PODWYKONAWCA'), (5, 'ODPADY'), (6, 'INNE')], default=0),
        ),
    ]
