# Generated by Django 4.1 on 2022-08-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0028_remove_przetarg_nazwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przetarg',
            name='budzet',
            field=models.PositiveIntegerField(default=None, verbose_name='BUDŻET'),
        ),
        migrations.AlterField(
            model_name='przetarg',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='DATA'),
        ),
        migrations.AlterField(
            model_name='przetarg',
            name='kod_pocztowy',
            field=models.CharField(max_length=128, verbose_name='KOD POCZTOWY'),
        ),
        migrations.AlterField(
            model_name='przetarg',
            name='miasto',
            field=models.CharField(max_length=128, verbose_name='MIASTO'),
        ),
        migrations.AlterField(
            model_name='przetarg',
            name='typ_budowy',
            field=models.CharField(max_length=128, verbose_name='TYP BUDOWLI'),
        ),
        migrations.AlterField(
            model_name='przetarg',
            name='typ_budynku',
            field=models.CharField(max_length=128, verbose_name='TYP BUDYNKU'),
        ),
        migrations.AlterField(
            model_name='przetarg',
            name='ulica',
            field=models.CharField(max_length=128, verbose_name='ULICA'),
        ),
        migrations.AlterField(
            model_name='przetarg',
            name='zleceniodawca',
            field=models.CharField(max_length=128, verbose_name='ZLECENIODAWCA'),
        ),
    ]
