# Generated by Django 4.1 on 2022-08-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0029_alter_przetarg_budzet_alter_przetarg_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budowa',
            name='kod_pocztowy',
            field=models.CharField(max_length=6),
        ),
    ]
