# Generated by Django 4.1 on 2022-08-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0030_alter_budowa_kod_pocztowy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budowa',
            name='kod_pocztowy',
            field=models.CharField(max_length=7),
        ),
    ]
